name: workflow111
on:
    push:
        branches:
            - 'v[0-9]*\.[0-9]*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check Commit Message
              run: |  
                if [[ $(git log --format=%B -n 1 $GITHUB_SHA) == '#NORUN'* ]]; then
                  exit 0 
                fi
              shell: bash
            - uses: actions/checkout@v4
            - name: Run Trivy vulnerability scanner in repo mode
              id: scanfunction
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'table'
                output: 'trivy-results.txt'
                severity: 'HIGH'
                exit-code: 1
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              if: always() && steps.scanfunction.outcome=='failure'
              env:
                SLACK_WEBHOOK: ${{ secrets.SUBMISSION_HOOK }}
                SLACK_MESSAGE: 'Failed trivy scan, see report for details.'
            - name: Upload to slack step
              uses: adrey/slack-file-upload-action@master
              if: always() && steps.scanfunction.outcome=='failure'
              with:
                  token: ${{ secrets.ROBOT_TOKEN }}
                  path: trivy-results.txt
                  channel: submission
            - uses: sigstore/cosign-installer@v3.1.1
              with:
               cosign-release: 'v2.2.0'
            - name: Build an image from Dockerfile
              run: |
                docker build -t hemiaomiao/cicd:${{ github.sha }} .
            -
             name: Set up QEMU1
             uses: docker/setup-qemu-action@v3
            -
             name: Set up Docker Buildx
             uses: docker/setup-buildx-action@v3
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.MY_DOKERNAME }}
                password: ${{ secrets.MY_DOKERPASSWORD }}
            
            - name: Build and push
              id: build-and-push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: hemiaomiao/cicd:${{ github.sha }}
            - name: Sign image with a key
              run: |
                  cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
              env:
                TAGS: "hemiaomiao/cicd"
                COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
                COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
                DIGEST: ${{ steps.build-and-push.outputs.digest }}
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_WEBHOOK: ${{ secrets.SUBMISSION_HOOK }}
                SLACK_MESSAGE: "*Name*: He Miao\n *MatriculationNumber*: A0285896B\n *Email*: e1221708@u.nus.edu\n *Repository*: ${{ github.server_url }}/${{ github.repository }}\n *DockerHubURL*: https://hub.docker.com/r/hemiaomiao/cicd/tags"
          
        